### ISSUE TITLE
do not ruin the permissions of the pip cache folder

### ISSUE THREAD

**Issue by luzfcb** [nicolargo/glancesautoinstall#12]
install python packages with `pip` as the superuser, using `sudo` without using the `-H` modifier, causes permissions issues in pip cache folder.

it was necessary, I run `sudo chown -R $USER $HOME/.cache/pip/` to correct the permissions

**Comment by luzfcb** [comment]
fixed in https://github.com/nicolargo/glancesautoinstall/commit/ad529459497e60277f137da1226c43b4421fa074

**Comment by luzfcb** [comment]
@nicolargo :pray: if not asking too much, could you mark this pull-request with the label "Hacktoberfest"

**Comment by iuandrei** [comment]
@luzfcb I used the command `curl -L https://bit.ly/glances | /bin/bash` to install Glances v2.11.1 with psutil v5.4.1.

I got several warnings because `sudo pip install` is used instead of `sudo -H pip install`:
- `sudo pip install --upgrade pip`
- `sudo pip install setuptools glances[action,batinfo,browser,cpuinfo,chart,docker,export,folders,gpu,ip,raid,snmp,web,wifi]`
- `sudo pip install --upgrade setuptools glances[action,batinfo,browser,cpuinfo,chart,docker,export,folders,gpu,ip,raid,snmp,web,wifi]`
- `sudo pip install --upgrade glances`

The script was executed on Ubuntu 16.04.

**Comment by luzfcb** [comment]
@nicolargo remove `-H `  see: https://github.com/nicolargo/glancesautoinstall/commit/a3a2b82b2ea39755f8a88d701465f096364c6f29

**Comment by luzfcb** [comment]
assuming that I am a normal linux user named `luzfcb`, with the HOME folder located in `/home/luzfcb` and the `$HOME` environment variable point to `/home/luzfcb` 

`sudo` **without** `-H` modifier will run the command with `root` permissions, but using the `$HOME` environment variable of the current user ( not the `root` )
`pip` use the `$HOME` environment variable to create a cache directory on `/home/luzfcb/.cache/pip/`, but all new files/directories will be created with `root` permission, and `root` only read permission, that is, the `luzfcb` user has no `write` or `read` permission to some of the directories inside `/home/luzfcb/.cache/pip/` .


`sudo` **with** `-H` modifier will run the command with `root` permissions and using the `root` user `$HOME` environment variable, and not the `$HOME` of the current user.

`pip` use the `$HOME` environment variable of `root` user to create a cache directory on `/root/.cache/pip/`,

**Comment by iuandrei** [comment]
@luzfcb thank you for the clarification.
